import {
  AUTH_PROVIDER_NAME,
  USER_STATUS,
  EMAIL_VERIFICATION_ACTION_TYPE,
  POLICY_TYPE,
  USER_ACTIVITY_LOG_ACTION_TYPE,
} from '@prisma/client';

export {
  AUTH_PROVIDER_NAME,
  USER_STATUS,
  EMAIL_VERIFICATION_ACTION_TYPE,
  POLICY_TYPE,
  USER_ACTIVITY_LOG_ACTION_TYPE,
};
